columns:
  trans_date_trans_time: datetime
  cc_num: int64
  merchant: string
  category: string
  amt: float64
  first: string
  last: string
  gender: string
  street: string
  city: string
  state: string
  zip: int64
  lat: float64
  long: float64
  city_pop: int64
  job: string
  dob: datetime
  trans_num: string
  unix_time: int64
  merch_lat: float64
  merch_long: float64
  is_fraud: int64
  trans_date: datetime
  trans_time: string

target_column: is_fraud
